config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :rooms, :path => "blk" do
    resource :subscriptions
  end

  #get "posts/unsubscribe/:unsubscribe_hash" => "posts#unsubscribe", :as => 'comment_unsubscribe'

  get :search, controller: "application"

  get "posts/unsubscribe/:unsubscribe_hash" => "posts#unsubscribe", :as => 
  "comment_unsubscribe"
  
  resources :posts do
    resource :vote, module: :posts
    resources :comments, module: :posts do
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }

  as :user do
    get 'signin' => 'devise/sessions#new'
    post 'signin' => 'devise/sessions#create'
    delete 'signout' => 'devise/sessions#destroy'
  end

  resources :welcome

 
  #root to: "home#invite"
  root to: "posts#index"


  constraints subdomain: "beta" do
   get "invite" => "home#invite"
  end


  resources :users, only: [:show], as: "profile", :path => "u"
  get "about" => "home#about_2"
  get "about_2" => "home#about"
  get "live" => "posts#index"
  get "invite" => "home#invite"
  get "newest" => "posts#newest"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:create, :destroy]

  def create
    @subscription = @room.subscriptions.where(user_id: current_user.id).first_or_create
    @room_id = @room.id

    respond_to do |format|
      format.html { redirect_to @room, notice: "You successfully subscribed to #{@room.name}"}
      format.js # create.js.erb
    end
  end

  def destroy
    @subscription = @room.subscriptions.where(user_id: current_user.id).first_or_create
    @subscription.destroy
    @room_id = @room.id

    respond_to do |format|
      format.html { redirect_to @room, notice: "You successfully unsubscribed to #{@room.name}"}
      format.js # destroy.js.erb
    end

  end

  private

    def set_room
      @room = Room.friendly.find(params[:room_id])
    end
end

app/views/subscriptions/_subscribed.js.erb
//debugger;
var subscribedBlock = document.getElementById("subscribed_block_<%= @room_id %>");
var subscribedCount = document.getElementById("subscribed_count");

subscribedBlock.innerHTML ="";
subscribedBlock.insertAdjacentHTML("beforeend", "<%= escape_javascript(render partial: 'subscriptions/subscription', room: @room) %>");

if(subscribedCount != null) {
	subscribedCount.innerHTML = "";
	subscribedCount.insertAdjacentHTML("beforeend", "<%= escape_javascript(@room.subscriptions.count.to_s) %>")
}

app/views/subscriptions/_subscription.html.erb
<% if user_signed_in?  %>
  <% unless current_user.rooms.include? @room %>
    <%= link_to "Subscribe", room_subscriptions_path(@room), method: :post, remote: true, class:"btn btn-black btn-small w-100 block text-center" %>
  <% else %>
    <%= link_to "Unsubscribe", room_subscriptions_path(@room), method: :delete, remote: true, class:"btn btn-outline btn-small w-100 block text-center"  %>
  <% end %>

<% else %>
  <%= link_to "Subscribe", new_user_session_path, class:"btn btn-black btn-small w-100 block text-center" %>
<% end %>

app/views/subscriptions/_subscription_index.html.erb
<% if user_signed_in?  %>
  <% unless current_user.rooms.include? room %>
    <%= link_to "Subscribe", room_subscriptions_path(room), method: :post, remote: true, class:"btn btn-black btn-small w-100 block text-center" %>
  <% else %>
    <%= link_to "Unsubscribe", room_subscriptions_path(room), method: :delete, remote: true, class:"btn btn-outline btn-small w-100 block text-center"  %>
  <% end %>

<% else %>
  <%= link_to "Subscribe", new_user_session_path, class:"btn btn-black btn-small w-100 block text-center" %>
<% end %>

app/views/subscriptions/create.js.erb
<% if current_page?(controller: "welcome", action: "show") %>
	<%= render "subscribed_index" %>
<% else %>
	<%= render "subscribed" %>
<% end %>

app/views/subscriptions/destroy.js.erb
<% if current_page?(controller: "welcome", action: "show") %>
	<%= render "subscribed_index" %>
<% else %>
	<%= render "subscribed" %>
<% end %>