config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :rooms, :path => "blk" do
    resource :subscriptions
  end

  #get "posts/unsubscribe/:unsubscribe_hash" => "posts#unsubscribe", :as => 'comment_unsubscribe'

  get :search, controller: "application"

  get "posts/unsubscribe/:unsubscribe_hash" => "posts#unsubscribe", :as => 
  "comment_unsubscribe"
  
  resources :posts do
    resource :vote, module: :posts
    resources :comments, module: :posts do
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }

  as :user do
    get 'signin' => 'devise/sessions#new'
    post 'signin' => 'devise/sessions#create'
    delete 'signout' => 'devise/sessions#destroy'
  end

  resources :welcome

 
  #root to: "home#invite"
  root to: "posts#index"


  constraints subdomain: "beta" do
   get "invite" => "home#invite"
  end


  resources :users, only: [:show], as: "profile", :path => "u"
  get "about" => "home#about_2"
  get "about_2" => "home#about"
  get "live" => "posts#index"
  get "invite" => "home#invite"
  get "newest" => "posts#newest"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord

	mount_uploader :room_image, RoomImageUploader

	belongs_to :user
  	has_many :posts

	has_rich_text :description
	has_rich_text :sidebar

  	has_many :subscriptions
  	has_many :users, through: :subscriptions

  	extend FriendlyId
  	friendly_id :title, use: :slugged

  	def should_generate_new_friendly_id?
   		title_changed?
  	end

  	def format_name
	    # the ! after gsub modifies the attribute. Whereas without it just returns it
	    self.name.titleize
	    self.name.gsub!(' ', '')
	end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  #before_action :authenticate_user!, expect: [:index, :show]
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :admins_rights, only: [:new]
  
  respond_to :js, :html, :json

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @rooms = Room.all
    @room_posts = @room.posts.paginate(page: params[:page], per_page: 10).order("created_at desc")
    @grouped_posts = @room_posts.group_by { |t| t.created_at.to_date }
    @order = params[:order]

    @grouped_posts.each do |day, posts|

      if params[:order] == "newest"
      
      else
        @grouped_posts[day] = posts.sort {|a, b| b.votes_count <=> a.votes_count }
      end
    end
  end

  # GET /rooms/new
  def new
    @room = current_user.rooms.build
    @room.user_id = current_user.id
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.build(room_params)
    @room.user_id = current_user.id

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :title, :description, :sidebar, :user_id, :room_image)
    end

    def correct_user
      unless @room.user_id == current_user.id
        redirect_to rooms_path, notice: "Not authorized to edit this room"

        #you must return false to halt
        false
      end
    end

    def admins_rights
      unless current_user.admin_rights == true
        redirect_to rooms_path, notice: "Not authorized to create a room"

        #you must return false to halt
        false
      end
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :room_image, class: "label" %>
    <label class="btn btn-white btn-small inline-flex items-center">
          <%= render_svg 'icons/image', styles: "fill-current text-gray-600 mr-2" %> Upload Image
          <%= form.file_field :room_image, class: "hidden" %>
    </label>
  </div>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :description, class: "label" %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="mb-6">
    <%= form.label :sidebar, class: "label" %>
    <%= form.rich_text_area :sidebar %>
  </div>

  <div class="mb-6">
    <%= form.submit class: "btn btn-gray btn-small"%>    
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div class="card flex flex-wrap items-center justify-between px-4 py-2">
  <div class="flex-1">
     <%= link_to room, class:"no-underline text-gray-700" do %>
      <p class="m-0 leading-tight">
        <span class="text-xs no-underline inline-flex items-center text-gray-700">
          <%= render_svg 'icons/conversation', styles: "w-3 fill-current text-gray-500 mr-1" %> blk/<%= room.name %>
        </span>
      </p>
      <h3 class="m-0 leading-tight text-base"><%= room.title %><h3>
    <% end %>
  </div>

  <div class="text-xs font-normal flex">
    <!--<div id="subscribed_block" class="my-6">
        <%#= render "subscriptions/subscription_index", room: room %>
    </div>-->

    <%= link_to room, class: "no-underline" do %>
      <%= render_svg 'icons/view', styles: "w-4 fill-current text-gray-500", title: "View" %>
    <% end %>
    <% if author_of(room)  %>
      <%= link_to edit_room_path(room), class: "no-underline ml-2" do %>
        <%= render_svg 'icons/edit', styles: "w-4 fill-current text-gray-500", title: "Edit" %>
      <% end %>

      <%= link_to room, class: "no-underline ml-2", method: :delete, data: { confirm: 'Are you sure?' } do %>
        <%= render_svg 'icons/delete', styles: "w-4 fill-current text-gray-500", title: "Delete" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/_room_header.html.erb
<div class="bg-black text-white">
  <div class="container py-10 px-24 mx-auto">
    <h1 class="lg:text-3xl text-lg">blk/<%= room.name %></h1>
  </div>
</div>

app/views/rooms/_sidebar.html.erb
<div class="rounded">
  <div class="px-8 pt-6 pb-8">
    <div class="m-0 leading-tight flex items-center justify-between">
      <span class="text-xs no-underline inline-flex items-center text-gray-600">
        <%= render_svg 'icons/conversation', styles: "w-3 fill-current text-gray-500 mr-1" %> blk/<%= room.name %>
      </span>
      <% if author_of(room) %>
        <%= link_to edit_room_path(room), class: "no-underline mr-2" do %>
          <%= render_svg 'icons/edit', styles: "w-4 fill-current text-gray-500", title: "Edit" %>
        <% end %>
      <% end %>
    </div>
    <h3 class="m-0 leading-tight text-lg"><%= room.title %></h3>


    <div id="subscribed_block" class="my-6">
        <%= render "subscriptions/subscription", room: room %>
    </div>

    <div class="flex flex-wrap justify-start items-center pt-2">
      <div class="w-1/2 border-r border-gray-400">
        <p class="m-0"><%= room.posts.count %></p>
        <p class="m-0 text-xs">
          <%= pluralize(room.posts.count, 'Post') %>
        </p>
      </div>
      <div class="w-1/2 pl-4">
        <p id="subscribed_count"class="m-0"><%= room.subscriptions.count %></p>
        <p class="m-0 text-xs">Subscribers</p>
      </div>
    </div>

    <hr class="border-b border-gray-400" />
    <br>
    <strong><h1>About Room</h1></strong>
    <hr class="border-b border-gray-400" />
    <div class="text-sm mb-6">
      <%= room.description %>
    </div>

    <strong><h1>blk/<%= room.name %> Rules</h1></strong>
    <hr class="border-b border-gray-400" />

    <div class="text-sm mb-6">
      <%= room.sidebar %>
    </div>

    <div>
      <%= link_to 'Create Post', new_post_path, class: "btn btn-small btn-black my-2 block text-center"  %>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<% content_for :room_label, "Edit Room" %>

  <% content_for :primary_content do %>
    <div class="lg:p-10 pt-10 pb-10 px-4">
      <h1 class="text-xl font-normal mb-6">Editing Room</h1>
      <%= render 'form', room: @room %>
    </div>
  <% end %>

  <% content_for :secondary_content do %>
    <div class="px-8 pt-6 pb-8">
      <%= render_svg 'community', styles: 'max-w-full h-auto mb-4' %>
      <h4>Edit <%= @room.title %> room on BLKroom</h4>
      <p class="text-sm italic">Each room requires the following:</p>
      <ul class="mt-1 pl-4">
        <li>Name</li>
        <li>Title</li>
        <li>Description</li>
      </ul>
    </div>
  <% end %>

<%= render "basic_layout" %>

app/views/rooms/index.html.erb
<% content_for :room_label, "All Rooms" %>

<% content_for :primary_content do %>
  <div class="lg:p-10 pt-10 pb-10 px-4">
    <h1 class="text-xl font-normal mb-6">All Rooms</h1>
    <%= render @rooms %>
  </div>
<% end %>


<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-8">

    <% if current_user.admin_rights == true %>
      <%= link_to 'Create Room', new_room_path, class: "btn btn-small btn-black my-2 block text-center" if user_signed_in? %>
    <% end %>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/rooms/new.html.erb
<% content_for :room_label, "Create room" %>

<% content_for :primary_content do %>
 <div class="lg:p-10 pt-10 pb-10 px-4">
    <h1 class="text-xl font-normal mb-6">Create a Room</h1>
    <%= render 'form', room: @room %>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-8">
    <%= render_svg 'community', styles: 'max-w-full h-auto mb-4' %>
    <h4>Create a new room on Blkroom</h4>
    <p class="text-sm italic">Each room requires the following:</p>
    <ul class="mt-1 pl-4">
      <li>Name</li>
      <li>Title</li>
      <li>Description</li>
    </ul>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/rooms/show.html.erb
<% content_for :room_label, @room.name %>

<div class="bg-black text-white">
  <div class="container py-10 px-24 mx-auto">
    <h1 class="lg:text-3xl text-lg">blk/<%= @room.name %></h1>
  </div>
</div>

<div class="flex flex-wrap px-2 lg:px-24 mt-2 lg:mt-8 container m-auto uppercase text-xs font-semibold">
      Popular discussions
  </div>

<div class="container lg:px-24 m-auto p-3 text-grey-darkest">
       <div class="flex flex-wrap -mx-2 mb-8">

        <% if @room_posts.exists? %>
          <div class="w-full md:w-2/3 pr-0 md:pr-6 mb-6">
          <div class="rounded-full float-right">
              <ul class="list-none p-0 pt-2 profile-tabs">
                <li class="inline-block mr-2" data-tab="profile_submissions">
                  <%= link_to "Popular", room_path, class: "link font-medium text-black hover:text-gray-900 py-3 text-sm" %>
                </li>| 
               <li class="inline-block mr-2">
                  <%= link_to "Newest", room_path(:order => "newest"), class: "font-medium text-black hover:text-gray-900 py-3 text-sm" %>
                </li>
              </ul>
            </div>
            <% if @grouped_posts.present? %>
              
                <% @grouped_posts.each do |day, posts| %>

                <div class="rounded-tl-lg rounded-tr-lg container m-auto clearfix mb-3 ml-2">
                  <div class="w-full md:w-2/3 pr-0 md:pr-6 mb-6">
                    <h5 class="text-xl font-bold float-left">
                      <% if day == Date.today  %>
                        Today
                      <% elsif day == Date.yesterday %>
                        Yesterday
                      <%else%>
                        <%= day.strftime("%B #{day.day.ordinalize}") %>
                      <% end %>      
                      </h5>
                  </div>
                </div>
                
                <div class="bg-white shadow rounded-sm">
                  <% posts.each do |post| %>
                      <%= render 'posts/post', post: post %>                      
                  <% end %>
                </div>

                <% end %>
            
            <% end %>


            <% if @post_wise_sorted_alerts.present? %>
              <% @post_wise_sorted_alerts.each do |hash_elements|%>
                <div class="rounded-tl-lg rounded-tr-lg container m-auto clearfix mb-3 ml-2">
                  <div class="w-full md:w-2/3 pr-0 md:pr-6 mb-6">
                    <h5 class="text-xl font-bold float-left">
                    </h5>
                  </div>
                </div>
                
                    <div class="bg-white shadow rounded-sm">
                      <% hash_elements.last.reverse_each do |post| %>
                        <%= render 'posts/post', post: post %>
                      <% end %>
                    </div>
              <% end %>
            <% end %>
          </div>
        <% end %>

        <div class="w-full md:w-1/3">
            <div class="bg-white shadow rounded-sm">
              <div class="rounded">
                  <div class="px-8 pt-6 pb-8">
                    <div class="m-0 leading-tight flex items-center justify-between">
                      <span class="text-xs no-underline inline-flex items-center text-gray-600">
                        <%= render_svg 'icons/conversation', styles: "w-3 fill-current text-gray-500 mr-1" %> blk/<%= @room.name %>
                      </span>
                      <% if author_of(@room) %>
                        <%= link_to edit_room_path(@room), class: "no-underline mr-2" do %>
                          <%= render_svg 'icons/edit', styles: "w-4 fill-current text-gray-500", title: "Edit" %>
                        <% end %>
                      <% end %>
                    </div>
                    <h3 class="m-0 leading-tight text-lg"><%= @room.title %></h3>


                    <div id="subscribed_block_<%= @room.id %>" class="my-6">
                        <%= render "subscriptions/subscription", room: @room %>
                    </div>

                    <div class="flex flex-wrap justify-start items-center pt-2">
                      <div class="w-1/2 border-r border-gray-400">
                        <p class="m-0"><%= @room.posts.count %></p>
                        <p class="m-0 text-xs">
                          <%= pluralize(@room.posts.count, 'Post') %>
                        </p>
                      </div>
                      <div class="w-1/2 pl-4">
                        <p id="subscribed_count"class="m-0"><%= @room.subscriptions.count %></p>
                        <p class="m-0 text-xs">Subscribers</p>
                      </div>
                    </div>

                    <hr class="border-b border-gray-400" />
                    <br>
                    <strong><h1>About Room</h1></strong>
                    <hr class="border-b border-gray-400" />
                    <div class="text-sm mb-6">
                      <%= @room.description %>
                    </div>

                    <strong><h1>blk/<%= @room.name %> Rules</h1></strong>
                    <hr class="border-b border-gray-400" />

                    <div class="text-sm mb-6">
                      <%= @room.sidebar %>
                    </div>

                    <div>
                      <%= link_to 'Create Post', new_post_path, class: "btn btn-small btn-black my-2 block text-center"  %>
                    </div>
                  </div>
                </div>
            </div>
        </div>
       </div>
  </div>



<%= render 'basic_layout' %>

<div class="flex flex-wrap lg:px-24 container m-auto text-center">
  <div class="w-full md:w-2/3 pr-0 md:pr-6 mb-6 inline">
      <%#== pagy_nav(@pagy) %> <%= will_paginate @room_posts %>
  </div>
</div>