config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :rooms, :path => "blk" do
    resource :subscriptions
  end

  #get "posts/unsubscribe/:unsubscribe_hash" => "posts#unsubscribe", :as => 'comment_unsubscribe'

  get :search, controller: "application"

  get "posts/unsubscribe/:unsubscribe_hash" => "posts#unsubscribe", :as => 
  "comment_unsubscribe"
  
  resources :posts do
    resource :vote, module: :posts
    resources :comments, module: :posts do
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }

  as :user do
    get 'signin' => 'devise/sessions#new'
    post 'signin' => 'devise/sessions#create'
    delete 'signout' => 'devise/sessions#destroy'
  end

  resources :welcome

 
  #root to: "home#invite"
  root to: "posts#index"


  constraints subdomain: "beta" do
   get "invite" => "home#invite"
  end


  resources :users, only: [:show], as: "profile", :path => "u"
  get "about" => "home#about_2"
  get "about_2" => "home#about"
  get "live" => "posts#index"
  get "invite" => "home#invite"
  get "newest" => "posts#newest"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	#include VoteCountable
	self.per_page = 10
	
	mount_uploader :post_image, PostImageUploader
	mount_uploader :post_video, PostVideoUploader

	has_many :comments, as: :commentable

	belongs_to :user
	belongs_to :room

	has_rich_text :body

	has_many :votes

	validates :room, presence: true
	validates :title, presence: true
	validates :body, length: { maximum: 8000 }
	validates :url, url: true, allow_blank: true
	validate :image_or_video
	validate :url_or_content

	extend FriendlyId
  	friendly_id :title, use: :slugged

  	def should_generate_new_friendly_id?
   		title_changed?
  	end

  	scope :most_voted, -> do
	    where(created_at: (Time.now - 7.days)..Time.now ) # created 7 days ago
	    .order('votes_count DESC')                        # ordered by votes_count
	    .limit(100)                                       # first 100
	end

	private

	def image_or_video
		unless post_image.blank? || post_video.blank?
			unless post_image.blank? ^ post_video.blank?
				errors.add(:base, "Add an image or video, not both")
			end
		end
	end

	def url_or_content
		unless url.blank? || body.blank?
			unless url.blank? ^ body.blank?
				errors.add(:base, "Add an valid URL or text content")
			end
		end
	end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
	before_action :set_commentable

	private

	def set_commentable
		@commentable = Post.friendly.find(params[:post_id])
	end
end

app/controllers/posts/votes_controller.rb
class Posts::VotesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_post
	
	def create
		@post.votes.where(user_id: current_user.id).first_or_create

		respond_to do |format|
	      format.html { redirect_to request.referrer }
	    end
	end

	def destroy
		@post.votes.where(user_id: current_user.id).destroy_all

		respond_to do |format|
	      format.html { redirect_to request.referrer }
	    end
	end

	private

	def set_post
      @post = Post.friendly.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index, :newest]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  respond_to :js, :html, :json

  # GET /posts
  # GET /posts.json
  def index
    @user = User.all
    @latest = User.where.not(username: [nil, ""])
    
    if user_signed_in?
        @posts = current_user.subscribed_posts.paginate(page: params[:page], per_page: 10).order("created_at desc")
        @random = Post.order("RANDOM()")

        #Retrives all post and divides into two groups todays messages and other messages
        @grouped_posts = @posts.group_by { |t| t.created_at.to_date }

        if @grouped_posts[false].present?
          #Create day wise groups of posts      
          @post_wise_sorted_alerts = @grouped_posts[false].group_by { |t| t.created_at.wday}
        end
    else
        @posts = Post.paginate(page: params[:page], per_page: 10).order("created_at desc")

        #Retrives all post and divides into two groups todays messages and other messages
        @grouped_posts = @posts.group_by { |t| t.created_at.to_date }

        if @grouped_posts[false].present?
          #Create day wise groups of posts      
          @post_wise_sorted_alerts = @grouped_posts[false].group_by { |t| t.created_at.wday}
        end  
    end

    @grouped_posts.each do |day, posts|
      @grouped_posts[day] = posts.sort {|a, b| b.votes_count <=> a.votes_count }
    end

    #my_temp_data  = @grouped_posts
    #@grouped_posts.each do |day, posts|
    #  if day == Date.today
    #    delete my_temp_data[day]
    #    my_temp_data["Today"] = posts
    #  end
    #end
    #@grouped_posts = my_temp_data

    today = Date.today # Today's date
    @days_from_this_week = (today.at_beginning_of_week..today.at_end_of_week).map
  end

  def newest
    @user = User.all
    @latest = User.where.not(username: [nil, ""])
    if user_signed_in?
        @posts = current_user.subscribed_posts.paginate(page: params[:page], per_page: 10).order("created_at desc")
        @popular = current_user.subscribed_posts.order(votes_count: :desc)
        @random = Post.order("RANDOM()")

        #Retrives all post and divides into two groups todays messages and other messages
        @grouped_posts = @posts.group_by { |t| t.created_at.to_date }

        if @grouped_posts[false].present?
          #Create day wise groups of posts      
          @post_wise_sorted_alerts = @grouped_posts[false].group_by { |t| t.created_at.wday}
        end
    else
        @posts = Post.paginate(page: params[:page], per_page: 10).order("created_at desc")

        #Retrives all post and divides into two groups todays messages and other messages
        @grouped_posts = @posts.group_by { |t| t.created_at.to_date }

        if @grouped_posts[false].present?
          #Create day wise groups of posts      
          @post_wise_sorted_alerts = @grouped_posts[false].group_by { |t| t.created_at.wday}
        end  
    end

    today = Date.today # Today's date
    @days_from_this_week = (today.at_beginning_of_week..today.at_end_of_week).map
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @room = @post.room
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        if params[:came_from] == "post"
          format.html { redirect_to :root, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        end
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def unsubscribe
    user = User.find_by_unsubscribe_hash(params[:unsubscribe_hash])
    user.update_attribute(:comment_subscription, false)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :url, :post_image, :post_video, :room_id, :votes_count)
    end

    def correct_user
      unless @post.user_id == current_user.id
        redirect_to posts_path, notice: "Not authorized to edit this post"

        #you must return false to halt
        false
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_actions.html.erb
<div class="pt-1 flex flex-wrap items-center">
  <div class="flex-1">
    <%= link_to post_path(post, anchor: "comments"), class: "no-underline mr-2 flex items-center" do %>
      <%= render_svg "icons/conversation", title: "Comments", styles: "fill-current text-gray-500 icon-sm hover:text-gray-600" %>
      <span class="text-sm text-gray-600 ml-2"><%= pluralize(post.comments.count, 'comment') %></span>
    <% end %>
  </div>

  <div class="flex items-center justify-end">
	  <% if author_of(post) %>

	    <%= link_to edit_post_path(post), class: "no-underline mr-2" do %>
	      <%= render_svg "icons/edit", title: "Edit", styles: "fill-current text-gray-500 icon-sm hover:text-gray-700" %>
	    <% end %>

	    <%= link_to post, method: :delete, class: "no-underline", data: { confirm: "Are you sure?" } do %>
	      <%= render_svg "icons/delete", title: "Delete", styles: "fill-current text-gray-500 icon-sm hover:text-gray-700" %>
	    <% end %>

	  <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="border-red-400 p-4 rounded border bg-red-100 mb-6">
      <h2 class="text-sm heading text-red-500"><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul class="text-sm mt-2 text-red-500 pl-4">
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

  <div class="mb-6 w-full lg:w-2/5">
    <div class="relative">
      <%= form.select(:room_id, Room.all.collect {|u| [u.name, u.id]}, { prompt: "Choose a room"}, { class: "select"}) %>
      

      <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
        <svg class="fill-current h-4 w-4" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      </div>
    </div>
  </div>

  <hr class="border border-gray-400 my-4"/>

  <div class="pb-10">
    <nav class="border-box">
      <ul id="nav-tab" class="tabs list-none flex flex-wrap justify-between">
        <li class="active w-1/3 text-center cursor-pointer" data-tab="text">
          <%= link_to "#text", class: "tab tab-first" do %>
            <%= render_svg "icons/text" %> Text
          <% end %>
        </li>

        <li class="w-1/3 text-center cursor-pointer" data-tab="image_video">
          <%= link_to "#image_video", class: "tab" do %>
            <%= render_svg "icons/image" %> Image/Video
          <% end %>
        </li>

         <li class="w-1/3 text-center cursor-pointer" data-tab="url">
          <%= link_to "#link", class: "tab tab-last" do %>
            <%= render_svg "icons/link" %> Link
          <% end %>
        </li>
      </ul>
    </nav>
  </div>

  <div class="mb-6">
    <%#= form.label :title, class:"label" %>
    <%= form.text_field :title, placeholder: "Title", class:"input"  %>
  </div>

  <div class="mb-6 text">
    <%#= form.label "Text", class: "label" %>
    <%= form.rich_text_area :body, placeholder: "Text (optional)", class: "input"  %>
  </div>

  <div class="mb-6 url">
    <%#= form.label :url, class: "label" %>
    <%= form.text_field :url, placeholder: "Url", class: "input" %>
  </div>

  <div class="image_video">
    <div class="mb-6">
      <%= form.label :post_image, class: "label" %>
      <label class="btn btn-white btn-small inline-flex items-center">
        <%= render_svg 'icons/image', styles: "fill-current text-gray-600 mr-2" %> Upload Image
        <%= form.file_field :post_image, class: "hidden" %>
      </label>
    </div>

    <div class="mb-6">
      <%= form.label :post_video, class: "label" %>
      <label class="btn btn-white btn-small inline-flex items-center">
        <%= render_svg 'icons/video', styles: "fill-current text-gray-600 mr-2 " %> Upload Video
        <%= form.file_field :post_video, class: "hidden" %>
      </label>
    </div>
  </div>

  <div class="mb-6">
    <%= form.submit 'Post', class: "btn btn-gray" %>
  </div>
<% end %>

app/views/posts/_form_welcome.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="border-red-400 p-4 rounded border bg-red-100 mb-6">
      <h2 class="text-sm heading text-red-500"><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul class="text-sm mt-2 text-red-500 pl-4">
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

  <div class="mb-6 w-full lg:w-2/5">
    <div class="relative">
      <%= form.select(:room_id, Room.all.collect {|u| [u.name, u.id]}, { prompt: "Choose a room"}, { class: "select"}) %>
      

      <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
        <svg class="fill-current h-4 w-4" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      </div>
    </div>
  </div>

  <hr class="border border-gray-400 my-4"/>

  <div class="pb-10">
    <nav class="border-box">
      <ul id="nav-tab" class="tabs list-none flex flex-wrap justify-between">
        <li class="active w-1/3 text-center cursor-pointer" data-tab="text">
          <%= link_to "#text", class: "tab tab-first" do %>
            <%= render_svg "icons/text" %> Text
          <% end %>
        </li>

        <li class="w-1/3 text-center cursor-pointer" data-tab="image_video">
          <%= link_to "#image_video", class: "tab" do %>
            <%= render_svg "icons/image" %> Image/Video
          <% end %>
        </li>

         <li class="w-1/3 text-center cursor-pointer" data-tab="url">
          <%= link_to "#link", class: "tab tab-last" do %>
            <%= render_svg "icons/link" %> Link
          <% end %>
        </li>
      </ul>
    </nav>
  </div>

  <div class="mb-6">
    <%#= form.label :title, class:"label" %>
    <%= form.text_field :title, placeholder: "Title", class:"input"  %>
  </div>

  <div class="mb-6 text">
    <%#= form.label "Text", class: "label" %>
    <%= form.rich_text_area :body, placeholder: "Text (optional)", class: "input"  %>
  </div>

  <div class="mb-6 url">
    <%#= form.label :url, class: "label" %>
    <%= form.text_field :url, placeholder: "Url", class: "input" %>
  </div>

  <div class="image_video">
    <div class="mb-6">
      <%= form.label :post_image, class: "label" %>
      <label class="btn btn-white btn-small inline-flex items-center">
        <%= render_svg 'icons/image', styles: "fill-current text-gray-600 mr-2" %> Upload Image
        <%= form.file_field :post_image, class: "hidden" %>
      </label>
    </div>

    <div class="mb-6">
      <%= form.label :post_video, class: "label" %>
      <label class="btn btn-white btn-small inline-flex items-center">
        <%= render_svg 'icons/video', styles: "fill-current text-gray-600 mr-2 " %> Upload Video
        <%= form.file_field :post_video, class: "hidden" %>
      </label>
    </div>
  </div>

  <div class="mb-6">
    <%= hidden_field_tag 'came_from', "post" %>
    <%= form.submit 'Post', class: "btn btn-gray" %>
  </div>
<% end %>

app/views/posts/_guidelines.html.erb
<h3 class="font-light mb-4">Posting to BLKroom</h3>
<ol class="list-decimal leading p-o text-sm">
	<li class="border-b font-semibold py-1">Think before you post</li>
  	<li class="border-b font-semibold py-1">Post black relevent content</li>
  	<li class="border-b font-semibold py-1">Please post all threads in the right section</li>
  	<li class="border-b font-semibold py-1">No bullying and harassing other members</li>
  	<li class="border-b font-semibold py-1">Look for the original source of content</li>
  	<li class="border-b font-semibold py-1">Don't create the same thread in different forums</li>
  	<li class="border-b font-semibold py-1">Search for duplicates before posting</li>
  	<li class="border-b font-semibold py-1">Read the community's rules</li>
</ol>

app/views/posts/_post.html.erb
<div class="border-b border-r border-l">
  <div class="p-2 pt-2 pb-2 flex items-start flex-wrap hover:bg-gray-100">

    <div id="votes">
      <%= render "posts/votes", post: post %>
    </div>

    <div class="ml-2">
      <%= link_to post do %>
        <%= image_tag post.post_image.large.url, class: "lg:w-24 w-full max-w-full" %>
      <% end if post.post_image.present? %>

      <%= link_to post do %>
        <%= video_tag post.post_video.url, class: "lg:w-24 w-full max-w-full" %>
      <% end if post.post_video.present? %>
    </div>

    <div class="flex items-start flex-1 pl-4">      
      <div class="flex-1 w-full">
        <h3 class="mb-0 flex flex-wrap items-center text-base">
          <% post_link = post.url.present? ? post.url : post %>
          <%= link_to post.title, post_link, class: "no-underline font-bold hover:text-gray-600" %>

          <% if post.url %>
            <span class="pl-2 text-xs font-normal font-mono text-blue-400 tracking-tight">
              <%= link_to truncate(post.url, length: 18), post.url, class:"no-underline" %>
            </span>
          <% end %>
        </h3>

        <%= link_to room_path(post.room), class:"no-underline text-gray-700 font-normal hover:text-gray-700 hover:underline text-sm inline-block" do %>
            blk/<%= post.room.name %>
        <% end %>

        <span class="mx-1 inline-block text-sm text-gray-700">•</span>

        <%= render 'posts/posted_by', post: post %>
        <%= render 'posts/actions', post: post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_posted_by.html.erb
<p class="text-gray-600 font-normal text-sm inline-block">
 Posted by <%= link_to "u/#{post.user.username}", profile_path(post.user), class: "no-underline text-gray-600 font-normal hover:text-gray-700 hover:underline" %>
 <%= time_ago_in_words(post.created_at) %> ago
</p>

<!-- profile_path(post.user) -->

app/views/posts/_votes.html.erb
<%  if user_signed_in? %>
	<% if current_user.votes?(post) %>
		<%= link_to post_vote_path(post), class: "bg-white-300 btn-white hover:bg-gray-400 text-gray-800 h-20 w-16 font-bold py-2 px-4 rounded inline-flex items-center", method: :delete, remote: true do %>
			<div class="text-orange-600 text-center font-medium text-sm upvote">
				<%= render_svg "icons/up-vote", title: "upvote", styles: "fill-current upvote" %>
				<%= post.votes.count %>
			</div>
		<% end %>
	<% else %>
		<%= link_to post_vote_path(post), class: "bg-white-300 btn-white hover:bg-gray-400 text-gray-800 h-20 w-16 font-bold py-2 px-4 rounded inline-flex items-center", method: :post, remote: true do %>
			<div class="text-center font-medium text-sm upvote">
				<%= render_svg "icons/up-vote", title: "upvote", styles: "fill-current upvote" %>
				<%= post.votes.count %>
			</div>
		<% end %>
	<% end %>
<% else %>
	<%= link_to new_user_session_path, class: "bg-white-300 btn-white hover:bg-gray-400 text-gray-800 h-20 w-16 font-bold rounded inline-flex items-center justify-center", method: :post do %>
		<div class="text-center font-medium text-sm upvote">
			<%= render_svg "icons/up-vote", title: "upvote", styles: "fill-current upvote" %>
			<%= post.votes.count %>
		</div>
	<% end %>
<% end %>

app/views/posts/edit.html.erb
<% content_for :community_label, "Edit Post" %>

<% content_for :primary_content do %>
  <div class="lg:p-10 pt-10 pb-10 px-4">
    <h1 class="text-xl font-normal mb-6">Edit Post</h1>
      <%= render 'form', post: @post %>
  </div>
<% end %>

<% content_for :secondary_content do %>
<div class="px-8 pt-6 pb-8">
  <div class="text-center my-4">
    <%= image_tag "submission.svg", class: "max-w-full w-1/2 inline" %>
  </div>
  <%= render "guidelines" %>
</div>
<% end %>

<%= render "basic_layout" %>

app/views/posts/new.html.erb
<% content_for :community_label, "Create Post" %>

<% content_for :primary_content do %>
  <div class="lg:p-10 pt-10 px4">
    <h1 class="text-xl font-normal mb-6">Create a post</h1>
    <%= render 'form', post: @post %>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-8">
    <div class="text-center my-4">
      <%= image_tag "submission.svg", class: "max-w-full w-1/2 inline" %>
      <%# render_svg "post", styles: "w-1/2 m-auto mb-1 h-22" %>
    </div>
    <%= render "guidelines" %>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/posts/show.html.erb
<% content_for :room_label, @post.room.name %>

<%= render 'rooms/room_header', room: @post.room %>

<%= content_for :primary_content do %>
  <div class="p-4 pb-10 pr-6">
    <div class="flex flex-row items-start justify-between">

      <!--<div class="post-voting text-xs pr-2">
        <%# render 'voting', post: @post %>
      </div> -->

    <div id="votes">
      <%= render "votes", post: @post %>
    </div>
  
    <div class="submission-content pl-3">
        <%= render "posted_by", post: @post %>

        <h1 class="text-xl font-bold"><%= @post.title %></h1>

        <div class="leading-normal text-base lg:pr-6 mb-5 border-b border-gray-200 lg:pr-6">

          <%= image_tag @post.post_image.large.url, class: "max-w-full my-2" if @post.post_image.present? %>

          <%= video_tag @post.post_video.url, class: "max-w-full my-2", controls: true if @post.post_video.present? %>

          <% if @post.url.present? %>
            <div class="p-3 border rounded my-2 flex justify-center items-center">
              <%= render_svg "icons/link", styles: "mr-2 text-gray-600 fill-current" %>
              <%= link_to @post.url, @post.url, class: "lg:text-xl text-lg no-underline" %>
            </div>
          <% end %>
          <div class="py-4">
            <%= @post.body if @post.body %>
          </div>
        </div>

        <%= render "actions", post: @post %>

        <% unless user_signed_in? %>
            <p class="text-sm text-gray-600 my-2"><%= link_to "Login", new_user_session_path, class: "link" %> or <%= link_to "Sign up", new_user_registration_path, class: "link" %> to comment.</p>
        <% else %>
            <%# render "comments/form" %>
        <% end %>

        <div id="comments" class="mt-6 border-t border-gray-200">

          <% if user_signed_in? %>
            <p class="text-sm text-gray-600 my-2">comment as <%= link_to current_user.username, profile_path, class: "link" %></p>
            <%= render partial: "comments/form", locals: { commentable: @post } %>
          <% end %>

          <%= render @post.comments.where(parent_id: nil) %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= content_for :secondary_content do %>
  <%= render 'rooms/sidebar', room: @post.room %>
<% end %>

<%= render 'basic_layout' %>

app/views/posts/unsubscribe.html.erb
<div class="max-w-xl my-16 m-auto p-10 rounded shadow bg-white flex items-center justify-between">
  <div class="flex-1">
    <h2 class="mt-4 text-gray-800 font-bold">Successfully unsubscribed</h2>
    <%= link_to "Return to BLKroom", root_path, class: "btn btn-gray btn-small inline-block mt-4" %>
  </div>

  <%= image_tag "illustration.svg", class: "w-64" %>
</div>